### ISSUE TITLE
Formula Compatability Checklist - M

### ISSUE THREAD

**Issue by runlevel5** [homebrew-ppc64le/homebrew-core#3]
The objective is to be able `brew install` all formulas in this category

* [ ] m2c
* [ ] m4
* [ ] mackup
* [ ] macosvpn
* [ ] mac-robber
* [ ] macvim
* [ ] madplay
* [ ] mad
* [ ] mafft
* [ ] mage
* [ ] magic-wormhole
* [ ] magnetix
* [ ] mahout
* [ ] mailcheck
* [ ] mailhog
* [ ] mailutils
* [ ] mairix
* [ ] makedepend
* [ ] makefile2graph
* [ ] makeicns
* [ ] makensis
* [ ] makepkg
* [ ] makepp
* [ ] make
* [ ] makeself
* [ ] malbolge
* [ ] mallet
* [ ] mame
* [ ] man2html
* [ ] man-db
* [ ] mandoc
* [ ] manticoresearch
* [ ] mapcrafter
* [ ] mapnik
* [ ] mapserver
* [ ] marathon-swift
* [ ] mariadb@10.1
* [ ] mariadb@10.2
* [ ] mariadb@10.3
* [ ] mariadb-connector-c
* [ ] mariadb-connector-odbc
* [ ] mariadb
* [ ] markdown
* [ ] marst
* [ ] mas
* [ ] masscan
* [ ] massren
* [ ] mat2
* [ ] math-comp
* [ ] matlab2tikz
* [ ] maven@3.2
* [ ] maven@3.3
* [ ] maven@3.5
* [ ] maven-completion
* [ ] maven
* [ ] maven-shell
* [ ] mavsdk
* [ ] mawk
* [ ] maxima
* [ ] maxwell
* [ ] mbedtls
* [ ] mbelib
* [ ] mboxgrep
* [ ] mcabber
* [ ] m-cli
* [ ] mcpp
* [ ] mcrypt
* [ ] md5deep
* [ ] md5sha1sum
* [ ] mda-lv2
* [ ] mdbook
* [ ] mdbtools
* [ ] mdcat
* [ ] mdds
* [ ] mdf2iso
* [ ] mdk
* [ ] mdp
* [ ] md
* [ ] mdr
* [ ] mdv
* [ ] mdxmini
* [ ] mecab-ipadic
* [ ] mecab-jumandic
* [ ] mecab-ko-dic
* [ ] mecab-ko
* [ ] mecab
* [ ] mecab-unidic-extended
* [ ] mecab-unidic
* [ ] mediaconch
* [ ] media-info
* [ ] mednafen
* [ ] megacmd
* [ ] megatools
* [ ] meilisearch
* [ ] memcached
* [ ] memcacheq
* [ ] memcache-top
* [ ] memtester
* [ ] menhir
* [ ] mercurial
* [ ] mercury
* [ ] mergelog
* [ ] mergepbx
* [ ] mesalib-glw
* [ ] mesa
* [ ] meson-internal
* [ ] meson
* [ ] mesos
* [ ] metabase
* [ ] metaproxy
* [ ] metashell
* [ ] metis
* [ ] metricbeat
* [ ] mfcuk
* [ ] mfoc
* [ ] mfterm
* [ ] mftrace
* [ ] mgba
* [ ] mg
* [ ] mhash
* [ ] micronaut
* [ ] micropython
* [ ] micro
* [ ] midgard2
* [ ] midicsv
* [ ] midnight-commander
* [ ] mighttpd2
* [ ] mikmod
* [ ] mikutter
* [ ] miller
* [ ] mill
* [ ] mimic
* [ ] minbif
* [ ] minetest
* [ ] mingw-w64
* [ ] minica
* [ ] minicom
* [ ] minidjvu
* [ ] minidlna
* [ ] minikube
* [ ] minimal-python
* [ ] minimal-racket
* [ ] minimesos
* [ ] minimodem
* [ ] minio-mc
* [ ] minio
* [ ] minipro
* [ ] minised
* [ ] miniserve
* [ ] minisign
* [ ] miniupnpc
* [ ] minizinc
* [ ] minizip2
* [ ] minizip
* [ ] mint
* [ ] minuit2
* [ ] miruo
* [ ] mitie
* [ ] mitmproxy
* [ ] mit-scheme
* [ ] mix-completion
* [ ] mjpegtools
* [ ] mkcert
* [ ] mkclean
* [ ] mk-configure
* [ ] mkcue
* [ ] mkdocs
* [ ] mkhexgrid
* [ ] mkl-dnn
* [ ] mksh
* [ ] mktorrent
* [ ] mkvalidator
* [ ] mkvdts2ac3
* [ ] mkvtomp4
* [ ] mkvtoolnix
* [ ] mlkit
* [ ] mlogger
* [ ] mlpack
* [ ] mlton
* [ ] mlt
* [ ] mmark
* [ ] mm-common
* [ ] mmctl
* [ ] mmix
* [ ] mmseqs2
* [ ] mmsrip
* [ ] mmv
* [ ] moarvm
* [ ] mobiledevice
* [ ] mockolo
* [ ] mockserver
* [ ] moco
* [ ] moc
* [ ] modd
* [ ] modgit
* [ ] modman
* [ ] modules
* [ ] moe
* [ ] mogenerator
* [ ] molecule
* [ ] molten-vk
* [ ] monero
* [ ] monetdb
* [ ] mongo-c-driver
* [ ] mongo-cxx-driver
* [ ] mongo-orchestration
* [ ] mongoose
* [ ] mongrel2
* [ ] mongroup
* [ ] monitoring-plugins
* [ ] monit
* [ ] monkeysphere
* [ ] mono-libgdiplus
* [ ] monolith
* [ ] mono
* [ ] mon
* [ ] montage
* [ ] moon-buggy
* [ ] moreutils
* [ ] morse
* [ ] mosh
* [ ] mosml
* [ ] mosquitto
* [ ] most
* [ ] movgrab
* [ ] moz-git-tools
* [ ] mozilla-addon-sdk
* [ ] mozjpeg
* [ ] mp3blaster
* [ ] mp3cat
* [ ] mp3check
* [ ] mp3fs
* [ ] mp3gain
* [ ] mp3info
* [ ] mp3splt
* [ ] mp3unicode
* [ ] mp3val
* [ ] mp3wrap
* [ ] mp4v2
* [ ] mpack
* [ ] mpage
* [ ] mpck
* [ ] mpc
* [ ] mpdas
* [ ] mpd
* [ ] mpdscribble
* [ ] mpdviz
* [ ] mpegdemux
* [ ] mpfi
* [ ] mpfr
* [ ] mpg123
* [ ] mpg321
* [ ] mpgtx
* [ ] mpi4py
* [ ] mpich
* [ ] mpir
* [ ] mplayer
* [ ] mplayershell
* [ ] mpop
* [ ] mpssh
* [ ] mps-youtube
* [ ] mpv
* [ ] mpw
* [ ] mrboom
* [ ] mr
* [ ] mrtg
* [ ] mruby-cli
* [ ] mruby
* [ ] mscgen
* [ ] msdl
* [ ] msgpack
* [ ] msgpack-tools
* [ ] msgpuck
* [ ] msitools
* [ ] msktutil
* [ ] msmtp
* [ ] mspdebug
* [ ] mstch
* [ ] mtoc
* [ ] mtools
* [ ] mtr
* [ ] mujs
* [ ] multimarkdown
* [ ] multitail
* [ ] muparser
* [ ] mupdf
* [ ] mupdf-tools
* [ ] mupen64plus
* [ ] mu
* [ ] musepack
* [ ] mussh
* [ ] mutt
* [ ] mvnvm
* [ ] mvtools
* [ ] mycli
* [ ] mydumper
* [ ] myman
* [ ] mypy
* [ ] mysql@5.6
* [ ] mysql@5.7
* [ ] mysql-client@5.7
* [ ] mysql-client
* [ ] mysql-connector-c++@1.1
* [ ] mysql-connector-c++
* [ ] mysql++
* [ ] mysql
* [ ] mysql-sandbox
* [ ] mysql-search-replace
* [ ] mysqltuner
* [ ] mytop
